name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
    - name: Check Modified Files
      run: echo ${{ steps.file_changes.outputs.files_modified}}
      
    - name: Run Authentication Library
      run: dotnet build ds.authentication/ds.authentication.csproj --configuration Release
      if: contains(steps.file_changes.outputs.files_modified, 'ds.authentication/ds.authentication.csproj' )
      
    - name: Run Authentication UI  
      run: dotnet build ds.authentication.ui.win/ds.authentication.ui.win.csproj --configuration Release
      if: contains(steps.file_changes.outputs.files_modified, 'ds.authentication.ui.win/ds.authentication.ui.win.csproj' )
    
    - name: Run DS Delmia MFG  
      run: dotnet build ds.delmia.mfg/ds.delmia.mfg.csproj --configuration Release
      if: contains(steps.file_changes.outputs.files_modified, 'ds.delmia.mfg/ds.delmia.mfg.csproj' ) 
