name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - id: file_changes
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - name: List all modified files
    - run: |
        readarray -t modified_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.modified }}')"
        for modified_file in ${modified_files[@]}; do
          echo "Do something with this ${modified_file}."
        done
        
    - name: Run Authentication Library
      run: dotnet build ds.authentication/ds.authentication.csproj --configuration Release
      if: contains(modified_files, 'ds.authentication/ds.authentication.csproj' )
      
    - name: Run Authentication UI  
      run: dotnet build ds.authentication.ui.win/ds.authentication.ui.win.csproj --configuration Release
      if: contains(modified_files, 'ds.authentication.ui.win/ds.authentication.ui.win.csproj' )
    
    - name: Run DS Delmia MFG  
      run: dotnet build ds.delmia.mfg/ds.delmia.mfg.csproj --configuration Release
      if: contains(steps.file_changes.outputs.modified_files, 'ds.delmia.mfg/ds.delmia.mfg.csproj' ) 
