name: Build 3DX .NET Core SDK Solution
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - id: file_changes
      uses: jitterbit/get-changed-files@v1
    - name: List all modified files
      run: echo "Do something with this ${{ steps.file_changes.outputs.modified }}."
        
    - name: Run Authentication Library
      run: dotnet build ds.authentication/ds.authentication.csproj --configuration Release
      if: contains( ${{ steps.file_changes.outputs.modified }}, 'ds.authentication/ds.authentication.csproj' )
      
    - name: Run Authentication UI  
      run: dotnet build ds.authentication.ui.win/ds.authentication.ui.win.csproj --configuration Release
      if: contains(( ${{ steps.file_changes.outputs.modified }}, 'ds.authentication.ui.win/ds.authentication.ui.win.csproj' )
    
    - name: Run DS Delmia MFG  
      run: dotnet build ds.delmia.dsmfg/ds.delmia.dsmfg.csproj --configuration Release
      if: contains( ${{ steps.file_changes.outputs.modified }}, 'ds.delmia.mfg/ds.delmia.mfg.csproj' ) 
