name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}\output

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
    - name: Check Modified Files
      run: echo ${{ steps.file_changes.outputs.files_modified}}
      
    - name: Pack and deploy Authentication Library to Nuget
      run: |
        dotnet pack ds.authentication/ds.authentication.csproj --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIR}}
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}\ds.authentication*.nupkg -k {{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
      if: contains(steps.file_changes.outputs.files_modified, 'ds.authentication/ds.authentication.csproj' )
      
    - name: Run Authentication UI  
      run: dotnet build ds.authentication.ui.win/ds.authentication.ui.win.csproj --configuration Release
      if: contains(steps.file_changes.outputs.files_modified, 'ds.authentication.ui.win/ds.authentication.ui.win.csproj' )
    
    - name: Run DS Delmia MFG  
      run: dotnet build ds.delmia.mfg/ds.delmia.mfg.csproj --configuration Release
      if: contains(steps.file_changes.outputs.files_modified, 'ds.delmia.mfg/ds.delmia.mfg.csproj' ) 
